### ISSUE TITLE
More than one ancestral genome

### ISSUE THREAD

**Issue by cerebis** [cerebis/meta-sweeper#28]
It would be useful if more than a single ancestor could be employed when defining a community

**Comment by cerebis** [comment]
In supporting more than one ancestral genome, additional information is required when configuring the sweep. In addition, we have the issue of generated (procedural) vs explicit tree and profile definitions. 

For the sake of information coherence and integrity, a structured is required. Since the config file of Nextflow seems to be lacking, I have been prototyping the definition in an ML (yaml, json) which will become the sweep configuration and be imported at runtime into the Nextflow script.

Each input ancestral sequence will become a set of related sequences and so I have chosen a nomenclature and preliminary structure as follows.

**NOTE** In the first instance, we will eliminate explicit file-based definitions of profiles and trees. If the need becomes sufficient, it will be reintroduced. As for now, we will have more realistic log-normal abundances and birth-death trees, while also supporting star phylogenies and uniform abundance for simpler needs. None of which is mutually exclusive.

Thus, the depiction of`clade2` below is no longer relevant.

``` yaml
clade1:
  ancestor: seq
  donor: seq
  ntax: 10
  tree: {birth: 1, death: 0.8}
  profile: {mu: 0.1, sigma: 1}
clade2:
  ancestor: seq
  donor: seq
  ntax: 5
  tree: {file: foo/bar.tre}
  profile: {file: blah/uniform.table}
```

Ties into issue #35
